-- local lazy_config = require "configs.lazy"

-- -- load plugins
-- require("lazy").setup({
--   -- {
--   --   "NvChad/NvChad",
--   --   lazy = false,
--   --   branch = "v2.5",
--   --   import = "nvchad.plugins",
--   -- },
--   { "nvchad/volt", },
--   { "nvchad/minty",            cmd = { "Shades", "Huefy" }, },
--   { "nvchad/menu", },
--   { "Bekaboo/deadcolumn.nvim", },
--   -- { import = "plugins" },
--   {
--     'Bekaboo/dropbar.nvim',
--     -- optional, but required for fuzzy finder support
--     dependencies = {
--       'nvim-telescope/telescope-fzf-native.nvim',
--       build = 'make'
--     }
--   },
--   {
--     "utilyre/barbecue.nvim",
--     name = "barbecue",
--     version = "1.2.0",
--     dependencies = {
--       "SmiteshP/nvim-navic",
--       "nvim-tree/nvim-web-devicons", -- optional dependency
--     },
--     opts = {}
--   },
--   {
--     "luckasRanarison/tailwind-tools.nvim",
--     name = "tailwind-tools",
--     build = ":UpdateRemotePlugins",
--     dependencies = {
--       "nvim-treesitter/nvim-treesitter",
--       "nvim-telescope/telescope.nvim", -- optional
--       "neovim/nvim-lspconfig",         -- optional
--     },
--     opts = {}                          -- your configuration
--   },
--   {
--     'nvim-lualine/lualine.nvim',
--     dependencies = { 'nvim-tree/nvim-web-devicons' },
--   },
--   { 'akinsho/toggleterm.nvim', version = "*", config = true }
-- }, lazy_config)

-- require("cmp").config.formatting = {
--   format = require("tailwindcss-colorizer-cmp").formatter
-- }

-- require("lualine").setup({ options = { theme = "nord" } })

-- -- vim.schedule(function()
-- --   require "mappings"
-- -- end)

-- require("telescope").load_extension("ui-select")
